version: 0.1.{build}

platform:
  - x64

cache:
  - node_modules

init:
  - git config --global core.autocrlf input

install:
  - npm i -g npm@5.2.0
  - npm install -g electron-packager
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run package

artifacts:
  - path: README.md
    type: file
  - path: release\StoreControl-win32-ia32\
    type: zip
  - path: release\StoreControl-linux-x64\
    type: zip
  - path: release\installer\StoreControlSetup.exe
    type: file

test: off

branches:
    only:
      - master
