version: "{build}"

platform:
  - x64

environment:
  nodejs_version: "8"

skip_tags: false
skip_non_tags: true

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%APPVEYOR_BUILD_FOLDER%\release -> cleanup-cache.txt'

install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  - ps: Install-Product node $env:nodejs_version
  - npm i -g npm@5.4.2
  - npm install -g electron-packager
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run pack-win && node ./script/installer.js
  - mkdir releaseNew
  - ps: mv "release\\installer\\StoreControl-$env:package_version-*.nupkg" releaseNew\
  - rm -f release/installer/*.nupkg
  - mv releaseNew/*.nupkg release/installer/

artifacts:
  - path: README.md
    type: file
  - path: release\StoreControl-win32-ia32\
    type: zip
  - path: release\installer\StoreControlSetup.exe
    type: file
  - path: release\installer\RELEASES
  - path: release\installer\**\*.nupkg

deploy:
- provider: GitHub
  tag: "%package_version%"
  auth_token:
    secure: ObLpbxWfj03jaKLe6RxHD7gwOqShvanaxxTPI1Eh20F+WzEqeaaUOeSTPXP8P1GJ
  on:
    branch: master
    appveyor_repo_tag: true

test: off

branches:
    only:
      - master
