image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules -> package.json
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - yarn dist

test: off
